name: ghcr镜像构建
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # 允许推送和修改仓库文件
      packages: write  # 允许推送到 GHCR
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
   
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/admin8800/3x-ui
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=pep440,pattern={{version}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
